services:
  pdf2estimate-server:
    container_name: pdf2estimate-container
    image: ghcr.io/redwan002117/pdf2estimate-app:main
    ports:
      - "6969:80"
    environment:
      - VITE_GEMINI_API_KEY=change_me

    restart: unless-stopped

# CasaOS Metadata
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: pdf2estimate-server
  description:
    en: "Pdf2Estimate is an AI-powered repair estimate converter tool."
  tagline:
    en: "AI Repair Estimate Converter"
  developer: "Redwan"
  author: "Redwan"
  icon: "https://raw.githubusercontent.com/Redwan002117/pdf2estimate-app/main/public/vite.svg"
  thumbnail: "https://raw.githubusercontent.com/Redwan002117/pdf2estimate-app/main/public/vite.svg"
  title:
    en: "Pdf2Estimate Pro"
  category: "Productivity"
  port_map: "6969"
